### ISSUE TITLE
Google Sheet Template - Formulas Used

### ISSUE THREAD

**Issue by gorfreed** [jawslouis/Battlegrounds-Match-Data#1]
Hello! Really great job on the plugin, your instructions for setting it up are spot-on and this is probably one of my smoothest Github "let's see if that works" projects :) 

Anyways, I wanted to ask you how the formulas work in your GS template and how the Graphs are generated. I copied the document but it doesn't seem to copy all of it as I just get #REF results for those. Can you help me out and post the calculation here?

Is it in any way realistic to have the results shown in a nice fancy dashboard at some point? It would be awesome not to have to fiddle around with spreadsheets in the first place. Let me know if you need a server to host it and we can put it on one of my unused Ubuntu Server machines (Apache2/php7, Wordpress vanilla install)!

**Comment by jawslouis** [comment]
Glad you found the plugin useful :)

I'm not sure which formula you're referring to, as there are several in use in the spreadsheet. If you can post a link to your sheet I can help take a look. 

Regarding the dashboard - sorry I don't have the bandwidth to work on that as I'm focusing on improving the plugin. The code base is available for others to build upon though :)

**Comment by jawslouis** [comment]
To update, the latest version of the plugin enables uploading to a dashboard. The instructions are in the repository README. Give it a go!
