### ISSUE TITLE
change of battletag

### ISSUE THREAD

**Issue by heIlo** [jawslouis/Battlegrounds-Match-Data#10]
hi, i recently changed my battletag on blizzard, so my old battletag and new battletag have separate pages on the dashboard. is it possible to merge them?

**Comment by jawslouis** [comment]
I can help you do this on the backend. What is your old battletag and new battletag?
And to confirm, you want all the games listed under your new battletag?

**Comment by heIlo** [comment]
hi, yes! 

my old battletag was Felix#13296 and my new one is jubjoe#11192

**Comment by jawslouis** [comment]
Ok I've done the update. Check the page for jubjoe#11192 and let me know if it's correct now?

**Comment by heIlo** [comment]
yep it works now, thank you!
