### ISSUE TITLE
Dashboad page at bgstats.cintrest.com blank

### ISSUE THREAD

**Issue by Geemonty** [jawslouis/Battlegrounds-Match-Data#11]
I was changing the date range on the dashboard and the page just went blank and no longer shows my data or any elements of the page.  The history page still shows info, however.

I am using chrome but I tested it on firefox as well.  In FF the UI flashes for a second then goes blank as well.

http://bgstats.cintrest.com/Gabriel-11451

**Comment by jawslouis** [comment]
I can see the page properly on my end, so this is probably your local storage settings being saved incorrectly. Try clearing the local storage and refreshing the page.
On the page, Right Click -> Inspect -> Application tab -> Right click on bgstats.cintrest.com (in the Storage sidebar, under Local Storage) -> Clear

**Comment by Geemonty** [comment]
OMG thank you so much.  I couldn't figure it out and it wasn't working on any of my browsers.  That did the trick.  I wonder why it would have done that when I change the time fame.
