### ISSUE TITLE
Problems with date

### ISSUE THREAD

**Issue by unw1s3** [jawslouis/Battlegrounds-Match-Data#12]
After uploading Todays stats to http://bgstats.cintrest.com/ I have got this in History -  September 11, 2020 11:11 PM.  (9/11/2020) Probably confused month and day. Date at my pc in dd/mm/yyyy format.

**Comment by jawslouis** [comment]
Thanks for bringing this to attention. I've updated the plugin that should fix this issue for future games. You can download the latest release at https://github.com/jawslouis/Battlegrounds-Match-Data/releases
