### ISSUE TITLE
Error: Message[Unable to parse range: Boards!A1:F] Location[ - ] Reason[badRequest] Domain[global]

### ISSUE THREAD

**Issue by JoeSham** [jawslouis/Battlegrounds-Match-Data#14]
Hi, I am trying to get the upload to GSheet to work, but for some reason it doesn't. I checked the logs and this errors keeps popping up everytime when the "Updating spreadsheet data" action happens. Can you please help me with it @jawslouis? Thx
[hdt_log_1610184245.txt](https://github.com/jawslouis/Battlegrounds-Match-Data/files/5790432/hdt_log_1610184245.txt)

```
9:26:58 AM|Info|SpreadsheetConnector.UpdateData >> Updating spreadsheet data
9:26:59 AM|Error|ActionList.Execute >> Error invoking action (Plugin: Battlegrounds Match Data):
The service sheets has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Unable to parse range: Boards!A1:F [400]
Errors [
	Message[Unable to parse range: Boards!A1:F] Location[ - ] Reason[badRequest] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at BattlegroundsMatchData.SpreadsheetConnector.UpdateData(IList`1 values, String range)
   at BattlegroundsMatchData.SpreadsheetConnector.WriteBoard(GameRecord record)
   at BattlegroundsMatchData.BgMatchData.TurnStart(ActivePlayer player)
   at Hearthstone_Deck_Tracker.API.ActionList`1.Execute(T arg) in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\API\ActionList.cs:line 39
```

**Comment by jawslouis** [comment]
Thanks for posting the log. The issue is that in the current version, there needs to be a sheet named "Boards" for it to work. You could either rename the sheet, or change the config file at `%userprofile%\AppData\Roaming\HearthstoneDeckTracker\Plugins\BattlegroundsMatchData\BattlegroundsMatchData.config`.   Edit the `SheetForAllBoards` line so it says `"SheetForAllBoards": "<your sheet name here>"` 

I realize the wiki instructions are also inconsistent with the current config. Will update the config file too.

**Comment by JoeSham** [comment]
Thx @jawslouis for the info. I changed the sheet name to `Boards` and now that sheet it works. But still nothing in sheet `MyResults` - should this also be named differently in the current version? Or does it get updated only after more games?

**Comment by jawslouis** [comment]
Yes it's a similar issue for the other sheet. In your version, it should be named to `Sheet1`.
The latest release that I've just posted has the correct names.

**Comment by JoeSham** [comment]
Ok, thanks for the help. And of course for this cool tool!

**Comment by jawslouis** [comment]
No problem. Glad you find it useful!
