### ISSUE TITLE
BGMatchDataBoards not working

### ISSUE THREAD

**Issue by OccamsUsername** [jawslouis/Battlegrounds-Match-Data#16]
Thank you so much for creating this plugin it's very helpful.  My issue is that the BGMatchDataBoard CSV file is not working for me.  The DataGames CSV works perfectly fine but the Boards doesn't work in any of the versions.  The file doesn't get created and when I create the file it stays blank.  I'm using standard settings for everything.  Much appreciated!

**Comment by jawslouis** [comment]
Hey thanks for filing this issue. There was a bug in the code that prevented the board CSV from being written. I've fixed it in the latest release, v0.4.7. It should work now!

**Comment by OccamsUsername** [comment]
Just tested the new release, working now!
