### ISSUE TITLE
Quilboar?

### ISSUE THREAD

**Issue by heIlo** [jawslouis/Battlegrounds-Match-Data#17]
Hi, does this need to be updated for the quilboar patch?

**Comment by jawslouis** [comment]
Sorry this comes late. The plugin is no longer maintained, will be looking for someone to take over.

**Comment by benluiwj** [comment]
Hi! Im the person that is currently taking over this plugin! I believe the issue you had here was on the website? I recently updated the website aspect of the plugin to include the current states of minions, heroes and types. Do check it out and let me know if you have any issues! If there are any further issues, do open an issue on the my fork [https://github.com/benluiwj/Battlegrounds-Match-Data](url). @heIlo
