### ISSUE TITLE
Plugin broken in new version of Hearthstone Deck Tracker

### ISSUE THREAD

**Issue by Istumi** [jawslouis/Battlegrounds-Match-Data#18]
Hi, 

Since the last update of Hearthstone Deck Tracker the plugin doesn't start at all with the following error:

> `System.ArgumentException: Empty path name is not legal.
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
>    at BattlegroundsMatchData.SpreadsheetConnector.Initialize(Config config)
>    at BattlegroundsMatchData.BgMatchDataPlugin.OnLoad()
>    at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in D:\a\Hearthstone-Deck-Tracker\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 93`

**Comment by hizenzen** [comment]
Will there be any fix, or this is the end of this plugin?

**Comment by jawslouis** [comment]
Sorry this comes late. The plugin is no longer maintained, I am now looking for someone who can take over from me.

**Comment by benluiwj** [comment]
Hi @hizenzen , @Istumi, I am the person who will be taking over from @jawslouis! Do create an issue on my fork, [https://github.com/benluiwj/Battlegrounds-Match-Data](url) and I will resolve it from there! Thanks!

**Comment by benluiwj** [comment]
Hi @hizenzen, I believe the plugin still works but now you would have to unzip the file and then add it to the plugins folder instead. Hope that helps! I will update the README to better reflect that! Sorry for the confusion!
