### ISSUE TITLE
Google Sheets sheet names do not match code

### ISSUE THREAD

**Issue by mstrkingdom** [jawslouis/Battlegrounds-Match-Data#4]
BgMatchDataPlugin.cs has `Sheet1` and `Boards` as the required names for the Google Sheets, but on the wiki, both the instructions for setup and config editing have "MyResults" and "AllBoards"

**Comment by jawslouis** [comment]
Thanks for bringing this to attention. `BgMatchDataPlugin.cs` uses the Sheet1 and Boards names as a default, but will use the names in the config file if it is specified there. Regardless, I've updated the naming in  `BgMatchDataPlugin.cs` to be consistent with the wiki.
