### ISSUE TITLE
Track Minion types in games

### ISSUE THREAD

**Issue by Shirkit** [jawslouis/Battlegrounds-Match-Data#5]
Is it possible to track which minion types were in a game?

At least start logging this for later use somehow, but saving this information could prove useful for a lot of players.

**Comment by jawslouis** [comment]
Unfortunately, it's currently not possible to track minion types available. The plugin can only use info that the deck tracker has, and this info is currently not recorded by the tracker. I can add this in, once the deck tracker also records this info.

**Comment by Shirkit** [comment]
I thought they were tracking somehow, due to they having a premium membership with minion types and minion comps.

**Comment by jawslouis** [comment]
The minion types and comps are based on minions bought and played on the board. But if the player never plays a beast or a murloc, for example, it's not possible to tell which minion type is not available in the game.

**Comment by Shirkit** [comment]
Would it possible to infer then based on bought minions from main player + opponents? If no player ever buys a beast whole game, prolly safe to infer that beasts were banned.

**Comment by jawslouis** [comment]
Update - since HDT has now started tracking minion types available, the info is also now tracked in the plugin too.
