### ISSUE TITLE
Deathwing saves as Bob´s Tavern in Boards Spreadsheet

### ISSUE THREAD

**Issue by olsanvit** [jawslouis/Battlegrounds-Match-Data#7]
Hi, 

when i meet Deathwing, he saved as Bob´s Tavern instead of his name in Google Spreadsheet. Where is the problem.

Thanks for anwer.

**Comment by jawslouis** [comment]
Thanks for bringing this up. I looked into it - this comes up in about 3.5% of cases. I think it happens when hearthstone indicates it's a new turn, but the opponent has not yet switched from Bob to the opponent hero. Still working on a fix, will update when I have one.

**Comment by jawslouis** [comment]
I published a new version that should fix the bug. 
You can download the latest from https://github.com/jawslouis/Battlegrounds-Match-Data/releases

**Comment by olsanvit** [comment]
Thanks a lot. 
I have a questions about this nice project. Is there another parameters, that we can take like a info ? For example archetype of result and archetype of each round ? Because i know, that BgStats take this information. Is there a chance to track 8 picked heroes and it finish position ? 
Or another idea is to get heroes pool before you pick one ? 
If you want to help with this project or just some ideas. I can participate, because i like your idea and make some cool statistics. 

Can I add you in Hearthstone ? If you want to add me, there is my battletag VitekCZ#2164 or you can contact me in my email olsanskyvitek@gmail.com

**Comment by olsanvit** [comment]
Thanks a lot.
I have a questions about this nice project. Is there another parameters,
that we can take like a info ? For example archetype of result and
archetype of each round ? Because i know, that BgStats take this
information. Is there a chance to track 8 picked heroes and it finish
position ?
Or another idea is to get heroes pool before you pick one ?
If you want to help with this project or just some ideas. I can
participate, because i like your idea and make some cool statistics.

Can I add you in Hearthstone ? If you want to add me, there is my battletag
VitekCZ#2164

čt 1. 10. 2020 v 11:03 odesílatel jawslouis <notifications@github.com>
napsal:

**Comment by jawslouis** [comment]
Hey thanks for the suggestions. While we can extract more info from the game, some info might not be so straightforward. For example, if tracking the results of the other heroes, we can only know the finishing positions of heroes that died before us. So if we finish 4th, we won't know the order of the top 3 finish. 

I'm currently working on another project, so I'm mainly doing maintenance and bug fixes for this project in the meantime. If you are able and willing to contribute to the code base via pull requests, I'm always happy to have further discussions or walk you through the code, so that you can implement it yourself.

**Comment by olsanvit** [comment]
Now im havent time to do it, because i must to write thesis, but after
that, i will help you with this project. Can i ask what are the project,
you are currently working on it ? It is somothing with Hearthstone ?

so 3. 10. 2020 v 3:02 odesílatel jawslouis <notifications@github.com>
napsal:

**Comment by jawslouis** [comment]
That's great! We can discuss more over email - I'll reach out.
