### ISSUE TITLE
update for new hero?

### ISSUE THREAD

**Issue by Zeuskk** [jawslouis/Battlegrounds-Match-Data#9]
In recent patch Battlegrounds received new hero Zephrys, the Great. Is there any chance for update?

**Comment by jawslouis** [comment]
The new heroes are automatically recorded, no update is necessary. 
If you're looking at localization/translation, that is something that I'll have to add on the backend. That will be out later on.

**Comment by jawslouis** [comment]
To update, I've now added the new hero localizations.
